name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test Code With Unitests
      run: python3 -m unittest -p "*_test.py"
        
  test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test Code With Unitests
      run: python3 -m unittest -p "*_test.py"
